version: '3'

services:
  shakecardsdb:
      container_name: shakecardsdb
      image: postgres:13.0
      environment:
        - POSTGRES_USER=shakecards
        - POSTGRES_PASSWORD=shakecardspass
        - POSTGRES_DB=shakecardsdb
      expose: 
        - 5432
      ports:
        - 5432:5432
  shakecardsweb:
      container_name: shakecardsweb
      build: .
      command: 'python3 manage.py runserver 0.0.0.0:8000'
      volumes:
        - .:/app
      ports:
        - '8000:8000'
      env_file:
        - '.env'
      depends_on:
        - shakecardsdb
