# Generated by Django 4.2.1 on 2023-11-20 01:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('colorTemplate', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Icon',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('icon', models.CharField(max_length=50, verbose_name='Icono')),
            ],
            options={
                'verbose_name': 'Icono',
                'verbose_name_plural': 'Iconos',
            },
        ),
    ]
