# Generated by Django 4.2.1 on 2023-11-20 03:04

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('colorTemplate', '0002_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='colorcompany',
            name='icono_services',
            field=colorfield.fields.ColorField(blank=True, default='#6246ea', image_field=None, max_length=25, null=True, samples=None, verbose_name='Icono Servicios'),
        ),
        migrations.AlterField(
            model_name='colorcompany',
            name='bg_main',
            field=colorfield.fields.ColorField(blank=True, default='#fffffe', image_field=None, max_length=25, null=True, samples=None, verbose_name='Fondo'),
        ),
        migrations.AlterField(
            model_name='colorcompany',
            name='company_icon',
            field=colorfield.fields.ColorField(blank=True, default='#fffffe', image_field=None, max_length=25, null=True, samples=None, verbose_name='Icono Empresa'),
        ),
        migrations.AlterField(
            model_name='colorcompany',
            name='company_main',
            field=colorfield.fields.ColorField(blank=True, default='#6246ea', image_field=None, max_length=25, null=True, samples=None, verbose_name='Empresa'),
        ),
        migrations.AlterField(
            model_name='colorcompany',
            name='company_secondary',
            field=colorfield.fields.ColorField(blank=True, default='#d1d1e9', image_field=None, max_length=25, null=True, samples=None, verbose_name='Empresa Secundario'),
        ),
        migrations.AlterField(
            model_name='colorcompany',
            name='icono_main',
            field=colorfield.fields.ColorField(blank=True, default='#6246ea', image_field=None, max_length=25, null=True, samples=None, verbose_name='Icono Principal'),
        ),
        migrations.AlterField(
            model_name='colorcompany',
            name='icono_secondary',
            field=colorfield.fields.ColorField(blank=True, default='#6246ea', image_field=None, max_length=25, null=True, samples=None, verbose_name='Icono Secundario'),
        ),
        migrations.AlterField(
            model_name='colorcompany',
            name='text_main',
            field=colorfield.fields.ColorField(blank=True, default='#2b2c34', image_field=None, max_length=25, null=True, samples=None, verbose_name='Texto Principal'),
        ),
        migrations.AlterField(
            model_name='colorcompany',
            name='text_secondary',
            field=colorfield.fields.ColorField(blank=True, default='#fffffe', image_field=None, max_length=25, null=True, samples=None, verbose_name='Texto Secundario'),
        ),
    ]
