# Generated by Django 4.2.1 on 2023-11-20 03:20

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('colorTemplate', '0003_colorcompany_icono_services_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='colorcompany',
            name='icono_utilities',
            field=colorfield.fields.ColorField(blank=True, default='#fffffe', image_field=None, max_length=25, null=True, samples=None, verbose_name='Icono Utilerias'),
        ),
        migrations.AlterField(
            model_name='colorcompany',
            name='icono_main',
            field=colorfield.fields.ColorField(blank=True, default='#2B2C34', image_field=None, max_length=25, null=True, samples=None, verbose_name='Icono Principal'),
        ),
    ]
