# Generated by Django 4.2.1 on 2023-10-19 22:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('mail', models.EmailField(max_length=254, verbose_name='Correo')),
                ('phone', models.CharField(max_length=15, verbose_name='Teléfono')),
                ('mobile', models.CharField(max_length=15, verbose_name='Celular')),
                ('whatsapp', models.CharField(max_length=15, verbose_name='Whatsapp Business')),
                ('web', models.URLField(verbose_name='Sitio Web')),
                ('schedule', models.CharField(max_length=100, verbose_name='Horario')),
                ('type', models.CharField(choices=[('USER', 'Usuario'), ('COMPANY', 'Empresa')], default='USER', max_length=10, verbose_name='Tipo')),
            ],
            options={
                'verbose_name': 'Contacto',
                'verbose_name_plural': 'Contactos',
            },
        ),
    ]
