# Generated by Django 4.2.1 on 2023-11-18 02:58

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('colorTemplate', '0001_initial'),
        ('user', '0001_initial'),
        ('service', '0001_initial'),
        ('contact', '0001_initial'),
        ('tool', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('slogan', models.CharField(max_length=50, verbose_name='Slogan')),
                ('logo', models.ImageField(upload_to='', verbose_name='Logo - Compañia')),
                ('cover', models.ImageField(upload_to='', verbose_name='Portada - Compañia')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='name', unique=True)),
                ('color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='colorTemplate.colorcompany', verbose_name='Tema')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card', to='contact.card')),
                ('service', models.ManyToManyField(to='service.service', verbose_name='Servicios')),
                ('tool', models.ManyToManyField(related_name='Utilerias', to='tool.utility')),
                ('user', models.ManyToManyField(to='user.user', verbose_name='Usuarios')),
            ],
            options={
                'verbose_name': 'Compania',
                'verbose_name_plural': 'Companias',
            },
        ),
    ]
