# Generated by Django 4.2.1 on 2023-11-20 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0003_alter_utility_logo'),
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='tool',
            field=models.ManyToManyField(blank=True, null=True, related_name='Utilerias', to='tool.utility'),
        ),
    ]
