# Generated by Django 4.2.1 on 2023-12-22 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0005_alter_utility_icon'),
        ('company', '0002_alter_company_tool'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='tool',
            field=models.ManyToManyField(blank=True, related_name='Utilerias', to='tool.utility'),
        ),
    ]
