# Generated by Django 4.2.1 on 2023-11-18 02:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Utility',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('decription', models.CharField(max_length=100, verbose_name='Descripción')),
                ('logo', models.ImageField(null=True, upload_to='', verbose_name='Logo - Icon')),
                ('url', models.URLField(verbose_name='URL')),
                ('type', models.CharField(choices=[('USER', 'Usuario'), ('COMPANY', 'Empresa')], default='USER', max_length=10, verbose_name='Tipo')),
            ],
            options={
                'verbose_name': 'Utileria',
                'verbose_name_plural': 'Utilerias',
            },
        ),
    ]
